// Generated by CoffeeScript 1.9.3
(function() {
  var $, GearSizeUI, events;

  GearSizeUI = require('./gear-size-events');

  $ = require('jquery')(window);

  GearSizeUI = new GearSizeUI();

  events = GearSizeUI.events;

  $(function() {
    GearSizeUI.emit(events.showAll);
  });

  $("#rim-diameter").click(GearSizeUI.emit(events.rimDiameterChanged));

  $("#tyre-size").click(GearSizeUI.emit(events.tyreChanged));

  $("#chainring").click(GearSizeUI.emit(events.chainRingsChanged));

  $('#cassette').click(GearSizeUI.emit(events.cassetteChanged));

  $('#show-all').click(GearSizeUI.emit(events.showAll));

  $('#show-comparison').click(GearSizeUI.emit(events.showComparison));

}).call(this);
