// Generated by CoffeeScript 1.9.3
(function() {
  var Settings;

  Settings = (function() {
    function Settings() {}

    Settings.rims = {
      diameters: [559, 622]
    };

    Settings.cassettes = {
      1123: [11, 12, 13, 14, 15, 16, 17, 19, 21, 23],
      1225: [12, 13, 14, 15, 16, 17, 19, 21, 23, 25],
      1228: [12, 13, 14, 15, 17, 19, 21, 23, 25, 28]
    };

    Settings.chainrings = {
      5339: [53, 39],
      5239: [52, 39],
      5242: [52, 42],
      5036: [50, 36],
      5034: [50, 34]
    };

    Settings.tyres = {
      sizes: [19, 22, 23, 25, 28, 32, 38]
    };

    return Settings;

  })();

  module(exports(Settings));

}).call(this);
